services:
  catalogDb:
    container_name: catalogDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalogDb:/var/lib/postgresql
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDb=Server=catalogDb;port=5432;Database=catalogdb;User Id=postgres;Password=postgres;Include Error Detail =true
    depends_on:
      - catalogDb
    ports:
      - "6060:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
  basketDb:
    container_name: basketDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basketDb:/var/lib/postgresql
